[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip RP235x"

[build]
target = "thumbv8m.main-none-eabihf"

[unstable]
build-std = ["core", "compiler_builtins"]

[env]
CC_thumbv8m_main_none_eabihf = "sccache arm-none-eabi-gcc"
